version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
  mongo-seed:
      build: mongo-seed/.
      links:
          - mongo
