version: "3"
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
  mongo-seed:
      build: mongo-seed/.
      links:
          - mongo
  # app:
  #   container_name: app
  #   restart: always
  #   build: app/
  #   ports:
  #     - "5000:5000"
